# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radaro < Formula
  desc "Self-hosted social listening and human-approved publishing in one binary"
  homepage "https://github.com/verrloren/radaro"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verrloren/radaro/releases/download/v0.1.0/radaro_0.1.0_darwin_amd64.tar.gz"
      sha256 "ff995b91db436cbf9cdf00030985b7656d7117af4ae5362578fe69a610bacc2b"

      define_method(:install) do
        bin.install "radaro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verrloren/radaro/releases/download/v0.1.0/radaro_0.1.0_darwin_arm64.tar.gz"
      sha256 "4832a51a31dd73851d8f800539e8d2d17dd5570fbb26875b3df5eaed02995bc4"

      define_method(:install) do
        bin.install "radaro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verrloren/radaro/releases/download/v0.1.0/radaro_0.1.0_linux_amd64.tar.gz"
      sha256 "fd0cd69cb9023f062b3707efcc9ab9f5df9d32f946149d15f9d9ba19bb7bee38"
      define_method(:install) do
        bin.install "radaro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verrloren/radaro/releases/download/v0.1.0/radaro_0.1.0_linux_arm64.tar.gz"
      sha256 "ec94da593d86bd3c2b46e4753fd716a60bbe493abe63ea01021e1859741576f9"
      define_method(:install) do
        bin.install "radaro"
      end
    end
  end

  test do
    system "#{bin}/radaro", "--version"
  end
end
